--JAVADB

--userTBL 테이블 생성
--NO(번호-숫자(4)), USERNAME(이름-한글 적어도 4자리), BIRTHYEAR(숫자 4자리), ADDR(주소-문자(한글+숫자) 넉넉히), MOBILE (010-1234-1234)

CREATE TABLE USERTBL (
NO NUMBER(4) CONSTRAINT PK_USERTBL PRIMARY KEY,
USERNAME VARCHAR2(12),
BIRTHYEAR NUMBER(4),
ADDR VARCHAR2(50),
MOBILE VARCHAR2(13)
);



-- 시퀀스 생성
-- USER_SEQ 생성(기본형태)
CREATE SEQUENCE USER_SEQ;

INSERT INTO USERTBL VALUES(USER_SEQ.NEXTVAL, '홍길동2', '1992', '활빈당' , '010-1231-2312');

select * from usertbl;

commit;

--모든 컬럼은 NOT NULL

--paytype 테이블 : pay_no(number-1 PK), info(문자-영어4자 CARD, CASH) 
    -- paytype_seq 생성

CREATE TABLE PAYTYPE (
PAY_NO NUMBER(1) CONSTRAINT PAYTYPE_PAY_NO_PK PRIMARY KEY,
INFO VARCHAR2(10) NOT NULL
);

CREATE SEQUENCE PAYTYPE_SEQ;

INSERT INTO PAYTYPE VALUES(PAYTYPE_SEQ.NEXTVAL, 'CARD');
INSERT INTO PAYTYPE VALUES(PAYTYPE_SEQ.NEXTVAL, 'CASH');

SELECT * FROM PAYTYPE;

-- Suser : user_id(숫자-4 PK), name(문자-한글), pay no(paytype 테이블 pay_no 참조) 

CREATE TABLE SUSER ( 
USER_ID NUMBER(4) CONSTRAINT SUSER_USER_ID_PK PRIMARY KEY, 
NAME VARCHAR2(20) NOT NULL, 
PAY_NO NUMBER(1) NOT NULL CONSTRAINT SUSER_PAY_NO_FK REFERENCES PAYTYPE(PAY_NO));

    
--product
    -- product_id (숫자-8 PK), pname(문자-넉넉) ,price(숫자), content(문자-feature들 들어올거)
    
CREATE TABLE PRODUCT(
PRODUCT_ID NUMBER(8) CONSTRAINT PRODUCT_PRODUCT_ID_PK PRIMARY KEY,
PNAME VARCHAR2(30) NOT NULL,
PRICE NUMBER(8) NOT NULL,
CONTENT VARCHAR2(50) NOT NULL);

CREATE SEQUENCE PRODUCT_SEQ;
    
--Sorder
    --order_id(숫자-8 PK), user_id(user테이블 참조), product_id(product 테이블 참조)
    --order_seq 생성
    
CREATE TABLE SORDER(
ORDER_ID NUMBER(8) CONSTRAINT SORDER_ORDER_ID_PK PRIMARY KEY,
USER_ID NUMBER(4) NOT NULL CONSTRAINT SORDER_USER_ID_FK REFERENCES SUSER(USER_ID),
PRODUCT_ID NUMBER(8) NOT NULL CONSTRAINT SORDER_PRODUCT_ID_FK REFERENCES PRODUCT(PRODUCT_ID));

CREATE SEQUENCE ORDER_SEQ;

SELECT * FROM SUSER;

select * from product;