-- 대소문자 구별하지 않음 (단, 비밀번호는 구별함)
--
-- CREATE : 생성 ALTER : 수정 DROP : 삭제 DELETE : 삭제
--
--오라클 버전이 변경되면서 사용자 생성 시 C## 문자를 넣어서 만들도록 변경 됨
--JAVADB -> C##JAVADB / 에서 C##을 사용하지 않겠음
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; 

-- USER 생성작업은 SYS, SYSTEM만 가능
-- USER 생성
-- CREATE USER id IDENTIFIED BY password
CREATE USER JAVADB IDENTIFIED BY 12345

-- CREATE한 USER가 사용할 공간을 할당
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

--GRANT : 권한 부여 (여기서는 CONNECT, RESOURCE) USER생성만으로는 어떤 작업도 할 수 없음
GRANT CONNECT, RESOURCE TO JAVADB;

CREATE USER SCOTT IDENTIFIED BY TIGER
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

--SCOTT에게 부여된 권한
GRANT CONNECT, RESOURCE TO SCOTT;
--뷰 생성 권한 부여
GRANT CREATE VIEW TO SCOTT;
--SYNONYM 생성 권한 부여
GRANT CREATE SYNONYM TO SCOTT;
GRANT CREATE PUBLIC SYNONYM TO SCOTT;


GRANT UNLIMITED TABLESPACE TO SCOTT;

SELECT * FROM ALL_USERS;

GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO SCOTT IDENTIFIED BY TIGER;
ALTER USER SCOTT DEFAULT TABLESPACE USERS;
ALTER USER SCOTT TEMPORARY TABLESPACE TEMP;
